#!/bin/bash

this_dir=$(cd "$(dirname "$0")" && pwd)
natlab="$this_dir/mclab/languages/Natlab/Natlab.sh"

$natlab -json -quiet "$@" >/tmp/stdout 2>/tmp/stderr
if [[ -s /tmp/stderr ]]; then
  cat /tmp/stderr
  exit 1
else
  cat /tmp/stdout
fi
